### ISSUE TITLE
Padrões de projeto para CSS/SCSS

### ISSUE THREAD

**Issue by nandomoreirame** [zen-team/zen-framework#8]
Salve Galera!
To vendo que a galera tá contribuindo bastante com o projeto, isso é legal.
Estou abrindo essa discussão para alinhar o padrão do código do Zen Framework, as últimas contribuições foram muito úteis para o projeto, mas parece que não estamos mantendo um padrão para a escrita dos arquivos.

Quem puder instale o plugin do [.editorconfig](http://editorconfig.org/) para manter o padrão de `2 espaços` , veja como foi estruturado o arquivo do projeto [aqui](https://github.com/zen-team/zen-framework/blob/master/.editorconfig).

Para padrões de escrita o que vocês acham de seguirmos o padrão do Github?
O Github tem um framework deles muito legal chamado [primercss](http://primercss.io/), vamos seguir o padrão da documentação deles [aqui](http://primercss.io/guidelines/)?

Se vocês tiverem alguma dica ou alguma documentação bacana e queiram sugerir comenta ai.

Obrigado!

**Comment by igorfelipee** [comment]
Não esqueçam de compilar o code antes de mandar o pull request. 
Nós estamos usando o sass para compilar os arquivos desse projeto :)
